server:
  port: 8070
spring:
  datasource:
    url: jdbc:postgresql://db:5432/nearbydb
    username: nearby
    password: nearby
  jpa:
    hibernate:
      ddl-auto: update
locationiq:
  api-key: pk.2c5852e18fa4920338724e4639a3d040
